### PR TITLE
Refactor CMake

### PR DESCRIPTION
**Pull request by Twon**
This pull request refactors the project CMake configured from the root of the repository as is standard for CMake projects.

### CODE REVIEW

**Comment by BobSteagall** [comment]
Can we un-delete the VS project files (.sln, .vxcproj, .filter)?  It is likely some folks will be unable/unwilling to use CMake on Windows.

**Comment by Twon** [comment]
Yes, I'll need to get access to a Windows virtual machine so I can try the solution under Visual Studio to ensure paths are correctly refactored.

Out of interest, and given CMake generated Visual Studio solutions what aspects of CMake do you consider to be problematic?  Thinking aloud here, but if there are concerns around ease of use of Conan/CMake or software requirements this could be hidden behind a setup script (presumably in Python).

**Comment by mpusz** [comment]
As a side note, from my experience, sooner or later one of the solutions will diverge from another. Trying to maintain both VS solutions and CMake is a huge pain because of this. You might end up with hard to reproduce problems or not consistent builds.

Taking into account that the latest versions of VS and VS Code work natively with CMake (no need to generate SLN files) I would suggest having only a CMake which is de-facto standard now in the C++ ecosystem.

**Comment by BobSteagall** [comment]
I don't see any deficiency in CMake _per se_, but a certain (probably large) percentage of Windows C++ programmers don't/won't use it.  I want them (and me) to have the convenience of the old-school VS project files.  

As far as divergence goes, given the relatively small number of files in this project, and the fact that the project lifetime is limited by approaching C++23 milestones, I'm am not worried about divergence.

**Comment by Twon** [comment]
As discussed offline I'll reinstate the Visual Studio solution and project file and then add a configuration in Appveyor to insure the Visual Studio build is successful.  Additionally, I'll open a ticket to track the creation of Nuget & VkPkg packages to provide alternative packaging options for users.

**Pull request merged**
